use winit::event::VirtualKeyCode;

pub fn u32_to_keycode(code: u32) -> Option<VirtualKeyCode> {
    match code {
        01 => Some(VirtualKeyCode::A),
        02 => Some(VirtualKeyCode::B),
        03 => Some(VirtualKeyCode::C),
        04 => Some(VirtualKeyCode::D),
        05 => Some(VirtualKeyCode::E),
        06 => Some(VirtualKeyCode::F),
        07 => Some(VirtualKeyCode::G),
        08 => Some(VirtualKeyCode::H),
        09 => Some(VirtualKeyCode::I),
        10 => Some(VirtualKeyCode::J),
        11 => Some(VirtualKeyCode::K),
        12 => Some(VirtualKeyCode::L),
        13 => Some(VirtualKeyCode::M),
        14 => Some(VirtualKeyCode::N),
        15 => Some(VirtualKeyCode::O),
        16 => Some(VirtualKeyCode::P),
        17 => Some(VirtualKeyCode::Q),
        18 => Some(VirtualKeyCode::R),
        19 => Some(VirtualKeyCode::S),
        20 => Some(VirtualKeyCode::T),
        21 => Some(VirtualKeyCode::U),
        22 => Some(VirtualKeyCode::V),
        23 => Some(VirtualKeyCode::W),
        24 => Some(VirtualKeyCode::X),
        25 => Some(VirtualKeyCode::Y),
        26 => Some(VirtualKeyCode::Z),

        27 => Some(VirtualKeyCode::Key0),
        28 => Some(VirtualKeyCode::Key1),
        29 => Some(VirtualKeyCode::Key2),
        30 => Some(VirtualKeyCode::Key3),
        31 => Some(VirtualKeyCode::Key4),
        32 => Some(VirtualKeyCode::Key5),
        33 => Some(VirtualKeyCode::Key6),
        34 => Some(VirtualKeyCode::Key7),
        35 => Some(VirtualKeyCode::Key8),
        36 => Some(VirtualKeyCode::Key9),

        37 => Some(VirtualKeyCode::Minus),
        38 => Some(VirtualKeyCode::Equals),
        39 => Some(VirtualKeyCode::LBracket),
        40 => Some(VirtualKeyCode::RBracket),
        41 => Some(VirtualKeyCode::Backslash),
        42 => Some(VirtualKeyCode::Semicolon),
        43 => Some(VirtualKeyCode::Apostrophe),
        44 => Some(VirtualKeyCode::Grave),
        45 => Some(VirtualKeyCode::Comma),
        46 => Some(VirtualKeyCode::Period),
        47 => Some(VirtualKeyCode::Slash),

        48 => Some(VirtualKeyCode::Space),
        49 => Some(VirtualKeyCode::Tab),

        50 => Some(VirtualKeyCode::Return),
        51 => Some(VirtualKeyCode::Back),
        52 => Some(VirtualKeyCode::Delete),
        53 => Some(VirtualKeyCode::Insert),

        54 => Some(VirtualKeyCode::PageUp),
        55 => Some(VirtualKeyCode::PageDown),
        56 => Some(VirtualKeyCode::Home),
        57 => Some(VirtualKeyCode::End),
        58 => Some(VirtualKeyCode::Up),
        59 => Some(VirtualKeyCode::Down),
        60 => Some(VirtualKeyCode::Left),
        61 => Some(VirtualKeyCode::Right),

        // 62 => Some(VirtualKeyCode::CapsLock),
        63 => Some(VirtualKeyCode::LControl),
        64 => Some(VirtualKeyCode::LShift),
        65 => Some(VirtualKeyCode::LAlt),
        _ => None,
    }
}
